# Params
[Params]
brand = 'Triangle Dong Dong'
brandtc = '三角東東'
brandLogo = ''
slogan = "專業的角度有趣地玩設計"
brandDescription = "創立於2020年，三角東東 Triangle Dong Dong 是一個專注於品牌設計的新創設計公司。 "


testimg = 'https://ucarecdn.com/16d84bf3-b31e-4a87-a82a-566364a85030/'

imgsm = '-/smart_resize/300x300/'
imgmd = '-/smart_resize/600x600/'
imglg = '-/smart_resize/900x900/'
imgxl = '-/smart_resize/1200x1200/'

imgResize = '-/smart_resize/'
imgAuto = '-/format/auto/'

imgProgress = '-/progressive/yes/'

# Navbar
[menu]
[[menu.main]]
  # Identifier must match the section name
  identifier = 'home'
  name = '首頁'
  title = '首頁'
  url = '/'
  weight = 1
[[menu.main]]
  identifier = 'about'
  name = '關於'
  title = '關於'
  url = '/about/'
  weight = 2
[[menu.main]]
  identifier = 'post'
  name = '文章'
  title = '查看部落格文章'
  url = '/post/'
  weight = 3
[[menu.main]]
  identifier = 'project'
  name = '專案'
  title = '查看作品'
  url = '/project/'
  weight = 4

# Taxonomy

[taxonomies]
  category = "categories"
  tag = "tags"
  project = "projects"

baseURL = '/'
languageCode = 'en-us'


# Markup Engine
enableEmoji = true
[markup]
  [markup.tableOfContents]
    endLevel = 4
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
