[[headers]]
for = "/*.jpg"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.png"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.css"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*.js"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/webfonts/*"

[headers.values]
Cache-Control = "public, max-age=604800"

[[headers]]
for = "/*"

[headers.values]
X-Frame-Options = "sameorigin"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "no-referrer"
Content-Security-Policy = "default-src 'self' 'unsafe-inline' 'unsafe-eval' 'unsafe-inline' www.google-analytics.com www.googletagmanager.com"