backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img

media_library:
  name: uploadcare
  config:
    publicKey: 5fa87fb5d63e84fccf01

collections:
