backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: static/img
public_folder: /img

media_library:
  name: uploadcare
  config:
    publicKey: 5fa87fb5d63e84fccf01

collections:
  # notes
  - name: "note"
    label: "筆記"
    folder: "content/post"
    create: true
    path: '{{slug}}/index'
    fields:
      - {label: "草稿", name: "draft", widget: "boolean", default: true, required: false}
      - label: "封面圖片"
        name: "cover"
        widget: "image"
        media_library:
          config:
            multiple: true
            previewStep: false
            

      - {label: "英文標題", name: "title", widget: "string"}
      - {label: "繁中標題", name: "titletc", widget: "string"}
      - {label: "簡介", name: "description", widget: "text"}
      - {label: "發布日期", name: "date", widget: "datetime", date_format: "YYYY-MM-DDTHH:mm:ssZ", format: "YYYY-MM-DDTHH:mm:ssZ", picker_utc: false }
      - {label: "類別", name: "categories", widget: "list", default: [""]}
      - {label: "標籤", name: "tags", widget: "list", default: ["tags"]}
      - label: "參與人員"
        name: "credites"
        widget: "list"
        fields:
          - {label: Credites Type, name: crediteType, widget: string, required: false}
          - label: "人物"
            name: "persons"
            widget: "list"
            fields:
              - label: "人"
                name: "person"
                widget: "object"
                collapsed: true
                fields:
                  - {label: "Person Name", name: "personName", widget: "string"}
                  - {label: "Person Link", name: "personLink", widget: "string", required: false}
      - {label: "顯示目錄", name: "toc", widget: "boolean", default: false}
      - {label: "內文", name: "body", widget: "markdown"}

  # Projects
  - name: "Project"
    label: "專案"
    summary: '{{fields.titletc}}-{{fields.title}}'
    folder: "content/project"
    create: true
    path: '{{slug}}/index'
    fields:
      - {label: "草稿", name: "draft", widget: "boolean", default: true}
      # - {label: "縮圖", name: "thumbnail", widget: "image", required: false}
      # - {label: "主視覺圖", name: "image", widget: "image", required: false}
      - {label: "英文標題", name: "title", widget: "string"}
      - {label: "繁中標題", name: "titletc", widget: "string"}
      - {label: "客戶", name: "client", widget: "string"}
      - {label: "簡介", name: "description", widget: "text"}
      - {label: "發布日期", name: "date", widget: "datetime", date_format: "YYYY-MM-DDTHH:mm:ssZ", format: "YYYY-MM-DDTHH:mm:ssZ", picker_utc: false }
      - {label: "開始日期", name: "dateStart", widget: "datetime", date_format: "YYYY-MM-DD", format: "YYYY-MM-DD", picker_utc: false }
      - {label: "結束日期", name: "dateEnd", widget: "datetime", date_format: "YYYY-MM-DD", format: "YYYY-MM-DD", picker_utc: false }
      - {label: "專案標籤", name: "projects", widget: "list", default: [""]}
      - {label: "內文", name: "body", widget: "markdown"}

      - label: "參與人員"
        name: "credites"
        widget: "list"
        fields:
          - {label: Credites Type, name: crediteType, widget: string, required: false}
          - label: "參與人員"
            name: "persons"
            widget: "list"
            fields:
              - label: "人"
                name: "person"
                widget: "object"
                collapsed: true
                fields:
                  - {label: "人名", name: "personName", widget: "string"}
                  - {label: "人的資料", name: "personInfo", widget: "string", required: false}
                  - {label: "人的連結", name: "personUrl", widget: "string", required: false}
